name: Build LaTeX document
on: 
  push:
    branches:
      - 'main'

env:
  CI_CD: "True"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Generate contents.tex
        run: python generate_pdf.py
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notebook.tex
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: notebook.pdf
          tag_name: ${{steps.date.outputs.date}}-livro-do-time
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
